// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCICGwkAk7zzAu-wHl32mz6NXcThKbtmiI',
    appId: '1:99592741858:web:97bfeadd6ce155b9e50fbb',
    messagingSenderId: '99592741858',
    projectId: 'flora-afd17',
    authDomain: 'flora-afd17.firebaseapp.com',
    storageBucket: 'flora-afd17.appspot.com',
    measurementId: 'G-GRSHS85R8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdmLomUfENMouPpPPrLZ9XnC9dncEP_Fc',
    appId: '1:99592741858:android:b187c6bb7b9dc791e50fbb',
    messagingSenderId: '99592741858',
    projectId: 'flora-afd17',
    storageBucket: 'flora-afd17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZnkifdIHelI4T8OZyEhchrLF35pBYY4g',
    appId: '1:99592741858:ios:a4bebf73e9cddd45e50fbb',
    messagingSenderId: '99592741858',
    projectId: 'flora-afd17',
    storageBucket: 'flora-afd17.appspot.com',
    iosBundleId: 'com.example.floraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZnkifdIHelI4T8OZyEhchrLF35pBYY4g',
    appId: '1:99592741858:ios:ec37c170c6697e5be50fbb',
    messagingSenderId: '99592741858',
    projectId: 'flora-afd17',
    storageBucket: 'flora-afd17.appspot.com',
    iosBundleId: 'com.example.floraApp.RunnerTests',
  );
}
